### ISSUE TITLE
write_dot and read_dot errors

### ISSUE THREAD

**Issue by quaxquax** [artiste-qb-net/quantum-fog#9]
Pulled the latest repo to retrace these steps. The networkx rendering works, but I get the following error message:

Traceback (most recent call last):
File "/home/quax/projects/quantum-fog/graphs/BayesNet.py", line 158, in
bnet.write_dot(path1)
File "/home/quax/projects/quantum-fog/graphs/Graph.py", line 258, in write_dot
nx.write_dot(self.get_nx_graph(), path)
AttributeError: module 'networkx' has no attribute 'write_dot'

**Comment by quaxquax** [comment]
The networkx write_dot issue seems to be related to this: nipy/nipype#1350

**Comment by quaxquax** [comment]
Errors disappear when referencing _nx.nx_pydot_ instead of _nx_.

Prepare a pull request.

**Comment by quaxquax** [comment]
No longer have this issue after a new Anaconda installation and a mint QFog environment.
